openapi: 3.0.1
info:
  title: monster-ankheg
  x-cortex-tag: monster-ankheg
x-cortex-custom-data:
  alignment: chaotic-neutral
  challenge_rating: 2
  legendary: false
  source: dnd-5e
  type: monstrosity
x-cortex-owners:
- email: bestiary@dnd.com
x-cortex-tag: monster-ankheg
x-cortex-type: monster
